name: GraalVM Community Edition build
on:
  push:
    branches:
      - '**'
    tags-ignore:
      - '**'
jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, windows-latest, ubuntu-latest]
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        id: setup-gradle-jdk
        with:
          distribution: temurin
          java-version: 17

      - uses: graalvm/setup-graalvm@v1
        with:
          java-version: '21'
          distribution: 'graalvm'
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2
        env:
          JAVA_HOME: ${{ steps.setup-gradle-jdk.outputs.path }}
        with:
          arguments: nativeCompile --scan

      - name: Upload binary
        uses: actions/upload-artifact@v3
        with:
          name: kafka-gitops-${{ matrix.os }}
          path: build/native/nativeCompile/kafka-gitops*
